
image:
  file: .gitpod.Dockerfile
#tasks:
#  - init: |
#      echo 'TODO: build project'
#    command: |
#      echo 'TODO: start app'
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
